Fix 1580
oscar-system/Oscar.jl pull request #1586
Opened 2022-09-30 17:02 UTC by HechtiDerLachs

This should fix https://github.com/oscar-system/Oscar.jl/issues/1580.

2022-09-30 18:30 UTC, simonbrandhorst requested changes
Looks reasonable and fixes the bug. 
Approved once you add the extra test.

2022-09-30 18:30 UTC, simonbrandhorst commented on experimental/Schemes/ProjectiveModules.jl
> +function Localization(A::MPolyLocalizedRing, f::MPolyLocalizedRingElem)
Please add a test.

2022-10-04 14:45 UTC, HechtiDerLachs commented
Let's see about the code coverage now. I added one test that should do the job.

2022-10-04 16:36 UTC, simonbrandhorst approved these changes

2022-10-04 16:39 UTC, merged