Make doctests part of Pkg.test()
oscar-system/Oscar.jl pull request #1768
Opened 2022-11-25 16:19 UTC by thofma

This allows for the downstream testing in our upstream packages GAP, Hecke, Polymake, etc., to also run the doctests by default (the downstream tests are run by default on julia version 1.6, so we are good in this regard).

A minor disadvantage is that the default julia version for https://github.com/oscar-system/OscarDevTools.jl and the Oscar 
doctest julia version need to be kept in lockstep.

(In an ideal world, we would make the doctests julia version agnostic and then these remarks about versions would all be unnecessary.)

CC: @fingolfin @benlorenz

2022-11-25 18:20 UTC, benlorenz commented
We do run the Oscar doctests already for the [Singular](https://github.com/oscar-system/Singular.jl/blob/master/.github/workflows/oscar.yml#L100) and [Polymake](https://github.com/oscar-system/Polymake.jl/blob/master/.github/workflows/oscar.yml#L105) OscarCI tests, they failed e.g. [here](https://github.com/oscar-system/Singular.jl/actions/runs/3542746033/jobs/5948577285).

2022-11-25 18:35 UTC, thofma commented
Ah, that would also be an option. At the moment all those config files need to update across all packages once we change the Oscar doctest julia version.

Does speak something against doing it directly in Pkg.test()? Should also make it faster since then the doctests are run in the same julia session.

2022-11-25 21:52 UTC, fingolfin commented on test/runtests.jl
> +  @info "Not running doctests (version must be 1.6)"
```suggestion
  @info "Running doctests (Julia version is 1.6)"
  DocMeta.setdocmeta!(Oscar, :DocTestSetup, :(using Oscar, Oscar.Graphs); recursive = true)
  doctest(Oscar)
else
  @info "Not running doctests (Julia version must be 1.6)"
```

2022-11-25 21:53 UTC, fingolfin commented
I see no obvious downsides (we also do this for GAP.jl). Perhaps @benlorenz can think of some?

On the upside, it makes `]test Oscar` more comprehensive.

2022-11-25 21:59 UTC, fingolfin commented
Tests fail due to some actual (minor) issues. I've pushed a fix (hopefully)

2022-11-26 00:59 UTC, benlorenz requested changes
I think the main reason for this should _not_ be the OscarCI downstream tests as we already have code for that in place which is working fine (and I think also reasonably easy to add to any repository).
I prefer to have different test-steps separate in the CI to make it easier to spot where a failure occurs, and also to make it easier to spot that the tests are running correctly. With the current setup I can directly see when the doctests are running for a job and when they are skipped. With this PR I would need to open the job log for the `tests` block, scroll to somewhere in the middle (after the installation / precompilation but before the other tests) and look for some `@info` block.

At least, I think we should swap the tests and run the doctests after the proper testsuite, which (at least in theory) should contain the more specific and more reliable tests that make it easier to pinpoint any failure. Parsing failures in the doctests is in my opinion way more annoying than parsing normal test failures.

PS: Just recently I did notice that the `Run tests`-step was running in about 10 minutes instead of 35 minutes because of many accidentally disabled tests. Including the doctests in that step would have made it less likely to be spotted that way, I could have blamed it on some of the usual fluctuations in the github actions performance instead.

2022-11-26 00:59 UTC, benlorenz commented on test/runtests.jl
> +if v"1.6.0" <= VERSION < v"1.7.0"
```suggestion
# We want to avoid running the doctests twice so we skip them when
# "oscar_run_doctests" is set by OscarDevTools.jl
if v"1.6.0" <= VERSION < v"1.7.0" && !haskey(ENV,"oscar_run_doctests")
```
This would hopefully simplify the transition, as it disables running the doctests when they will be run by the OscarCI anyway. (Or we can keep this in to allow the steps to be separate in the CI)

2022-11-26 01:16 UTC, benlorenz commented
> Ah, that would also be an option. At the moment all those config files need to be updated across all packages once we change the Oscar doctest julia version?

Currently yes, but we could probably put that version number in an environment variable instead which is set by `OscarDevTools.jl`, then we can just write it once in that repo (or we might even parse it from some file in the oscar repository).

2022-11-26 11:59 UTC, thofma commented
I have no strong opinion. I am also happy to just amend the OscarCI.yml in the other packages and leave everything as is.

It is just a bit odd in my opinion, that for the purpose of coverage we count also the `doctest(Oscar)` run, but we do not consider it part of the official tests. I believe it would simplify the development, since no one would need to remeber `Oscar.doc_build(;doctest = true)` for running the doctests (in yet another julia session).

2022-11-26 12:42 UTC, benlorenz commented
I would be fine with running the doctests within the normal tests (but please move them after the other tests), and using something like ` && !haskey(ENV,"oscar_run_doctests")` (or some other variable name) to skip them in the CI where we want to run them separately.

Also, I think it would be preferable to cover all code with normal tests as this makes sure that it runs correctly with all julia versions.

2022-11-26 14:35 UTC, thofma commented
Agreed. I will make the changes.

2022-11-26 19:56 UTC, thofma commented
Thanks for your feedback. I have moved the doctests to the end.

2022-11-28 11:31 UTC, benlorenz commented
> Thanks for your feedback. I have moved the doctests to the end.

Thanks! Fixes for the doctests are (almost) ready to merge in #1769 (it will merge into this PR here).

2022-11-28 13:22 UTC, benlorenz approved these changes

2022-11-28 16:33 UTC, merged