add docstrings for `acting_group` and `action_function`
oscar-system/Oscar.jl pull request #3432
Opened 2024-02-26 14:22 UTC by mjrodgers

Addresses parts of #3370

2024-02-26 14:26 UTC, lgoettgens commented on src/Groups/gsets.jl
>  # TODO: document `acting_group`, `action_function`
```suggestion
```

2024-02-26 15:41 UTC, ThomasBreuer requested changes
Thanks. Just a few useful additions:
- The documentation for the two functions should be mentioned in `docs/src/Groups/action.md`.
- `action_function` should be added to `src/exports.jl`.
- Some doctests could be added.

2024-02-26 15:41 UTC, ThomasBreuer commented on src/Groups/gsets.jl
> +Return the group `G` acting on `Omega`.
Perhaps add a doctest:
```
# Examples
```jldoctest
julia> G = symmetric_group(4);

julia> acting_group(gset(G, [1])) == G
true
```

2024-02-26 15:41 UTC, ThomasBreuer commented on src/Groups/gsets.jl
> +Return the function $f: \Omega \times G \to \Omega$ that defines the G-set.
Perhaps add a doctest:
```
# Examples
```jldoctest
julia> G = symmetric_group(4);

julia> action_function(gset(G, [1])) == ^
true

julia> action_function(gset(G, [[1, 2]])) == on_tuples
true

julia> action_function(gset(G, on_sets, [[1, 2]])) == on_sets
true
```

2024-02-26 15:41 UTC, fingolfin commented
Thanks that's a good start, but we should also verify that those functions are actually exported - I don't think they are (at least not both).

Perhaps you could add a simple `jldoctest` to both docstrings showing these functions, I think this then also automatically checks that they are exported.

2024-02-26 15:42 UTC, fingolfin commented
It seems @ThomasBreuer and me had the same thoughts at about the same moment, so our comments crossed :-)

2024-02-26 15:44 UTC, fingolfin commented on src/Groups/gsets.jl
> +Return the function $f: \Omega \times G \to \Omega$ that defines the G-set.
BTW to add a code block which contains triple backticks... you can simply use quadruple backticks (and so on). E.g.
`````
````
This is triple-quoted doctest code block:
```jldoctest
julia> 1+1
2
```
````
`````
results in this:
````
This is triple-quoted doctest code block:
```jldoctest
julia> 1+1
2
```
````

2024-02-27 11:58 UTC, fingolfin approved these changes

2024-02-27 12:04 UTC, lgoettgens commented
> The documentation for the two functions should be mentioned in docs/src/Groups/action.md.

This request of @ThomasBreuer is still open

2024-02-27 12:05 UTC, mjrodgers commented
> This request of @ThomasBreuer is still open

Thanks, I overlooked this one - I will update now

2024-02-27 12:11 UTC, ThomasBreuer approved these changes
Thanks, looks good.

2024-02-27 12:13 UTC, mjrodgers commented
Okay, this should have everything addressed now. I also mentioned using `collect(Omega)` to obtain the underlying G-set in `action.md`, so this should suffice to address everything now from #3370

2024-02-27 21:22 UTC, merged

2024-02-27 22:12 UTC, lgoettgens commented
Backport? Most of this is just documentation enhancements

2024-02-29 11:10 UTC, benlorenz commented
The new exports are used in the groups chapter, adding it to the backports list.