WIP on elliptic fibrations again
oscar-system/Oscar.jl pull request #3609
Opened 2024-04-15 10:19 UTC by HechtiDerLachs

CC: @simonbrandhorst

2024-04-16 13:33 UTC, simonbrandhorst requested changes

2024-04-16 13:33 UTC, simonbrandhorst commented on docs/src/AlgebraicGeometry/Schemes/MorphismsOfProjectiveSchemes.md
> +    morphism(X::AbsProjectiveScheme, Y::AbsProjectiveScheme, a::Vector{<:RingElem})
please deprecate

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/IdealSheaves.jl
> +      if !is_one(cheap_sub_ideal(I, U))
```suggestion
    k = findfirst(x->x isa PrimeIdealSheafFromChart, J)
    if k !== nothing
      # find a chart where we can cheaply compute a summand
      P = J[k]
      U = original_chart(P)
      if !is_one(cheap_sub_ideal(I, U))
```

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/IdealSheaves.jl
> +    end
could be moved to the front

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/IdealSheaves.jl
> +    #@assert is_one(result) || is_prime(result)
could be turned into an `hassert` with an assertion level.

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/IdealSheaves.jl
> +    iso = _flatten_open_subscheme(U, U2)
```suggestion
    iso = _flatten_open_subscheme(U, U2)  # an embedding U -> V \subseteq U2
```

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/IdealSheaves.jl
> +    result = ideal(OO(U2), [g for g in OO(U2).(lifted_numerator.(gens(pb_P))) if !iszero(g)])
```suggestion
    pb_P = pullback(iso_inv)(P)
    # avoids a saturation by discarding denominators but only produces a subideal
    result = ideal(OO(U2), [g for g in OO(U2).(lifted_numerator.(gens(pb_P))) if !iszero(g)])
```

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/IdealSheaves.jl
> +    @show complexity(W)
```suggestion
```

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/MorphismFromRationalFunctions.jl
>    # Try to cancel the fractions heuristically
```suggestion
  # Try to cancel the fractions heuristically; turns out it was too expensive in some applications due to slow divide
```

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/MorphismFromRationalFunctions.jl
> +
Is this in use? Should it stay? Can it go?

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/MorphismFromRationalFunctions.jl
> +function ideal_sheaf_of_image(phi::MorphismFromRationalFunctions)
to be evaluated

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/Sheaves.jl
>    return OO(U)(a, check=check)
looks strange, please check

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/Types.jl
> +A lazy type for a morphism ``φ : X → Y`` of `AbsCoveredScheme`s which is given
```suggestion
A lazy type for a dominant morphism ``φ : X → Y`` of `AbsCoveredScheme`s which is given 
```

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/Types.jl
> +    #_find_chart(U, default_covering(X)) !== nothing || error("patch not found in domain")
```suggestion
    @check is_irreducible(Y) "codomain must be irreducible"
    @check dim(Y) <= dim(X) "cannot be dominant"
    #_find_chart(U, default_covering(X)) !== nothing || error("patch not found in domain")
```

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/WeilDivisor.jl
> +        if !has_dimension_leq_zero(I)
```suggestion
        if !has_dimension_leq_zero(I) # potentially faster for localized ideals
```

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/WeilDivisor.jl
> +@attr function has_dimension_leq_zero(I::Ideal)
could be documented

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/WeilDivisor.jl
> +        end
```suggestion
        isone(J) && break
```

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/WeilDivisor.jl
> +        push!(patches_done, U)
```suggestion
        # push!(patches_done, U)
```

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/critical_locus.jl
> +function ideal_sheaf_of_critical_locus(phi::AbsCoveredSchemeMorphism)
Please document

Add a method
`critical_locus(phi::AbsCoveredSchemeMorphism) -> CoveredScheme, Morphism` 
?

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/critical_locus.jl
> +function ideal_sheaf_of_critical_locus(phi::AbsCoveredSchemeMorphism)
do we need the codomain to be smooth? check it?

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/elliptic_surface.jl
> +    I_sing_X0 = vcat(I_sing_X0, maximal_associated_points(I_sing_new))
```suggestion
    I_sing_X0 = vcat(maximal_associated_points(I_sing_new), I_sing_X0)
```

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/elliptic_surface.jl
> +      continue
needs a proof that this is just as fast

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/elliptic_surface.jl
> +end
Let us call this `fibration`. Should be a field of `X`.  
This should be a morphism. No need to get it from rational functions.
use `weierstrass_contraction` and compose it. 
We can give the weierstrass_model a 3rd output as the projection to `P^1`

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/elliptic_surface.jl
> +function _pushforward_lattice_along_isomorphism(step::MorphismFromRationalFunctions{<:EllipticSurface, <:EllipticSurface})
TODO comment

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/elliptic_surface.jl
> +end
```suggestion
```
Does not work.

2024-04-16 13:33 UTC, simonbrandhorst commented on src/AlgebraicGeometry/Schemes/AffineSchemes/Morphisms/Constructors.jl
> +#=
Seems to be duplicated from `src/AlgebraicGeometry/Schemes/AffineSchemes/Morphisms/Methods.jl`
double check and remove.

2024-04-16 13:33 UTC, simonbrandhorst commented on src/AlgebraicGeometry/Schemes/ProjectiveSchemes/Morphisms/Methods.jl
> +  # We skip the glueings for the time being.
```suggestion
  # We skip the gluings for the time being.
```

2024-04-16 13:33 UTC, simonbrandhorst commented on src/AlgebraicGeometry/Schemes/ProjectiveSchemes/Morphisms/Methods.jl
> +  inherit_glueings!(CC, default_covering(X))
```suggestion
  CC = Covering(collect(keys(mor_dict)), IdDict{Tuple{AbsAffineScheme, AbsAffineSchemeMor}, AbsGluing}())
  inherit_gluings!(CC, default_covering(X))
```
faulty merge

2024-04-16 13:33 UTC, simonbrandhorst commented on src/Modules/ModulesGraded.jl
> +
checkout this file just a change of blank lines.

2024-04-16 13:33 UTC, simonbrandhorst commented on src/Modules/UngradedModules/FreeModuleHom.jl
> -
same

2024-04-16 13:33 UTC, simonbrandhorst commented on src/Rings/MPolyMap/AffineAlgebras.jl
> +  @assert coefficient_ring(domain(f)) === coefficient_ring(codomain(f))
```suggestion
  @assert coefficient_ring(domain(f)) === coefficient_ring(codomain(f))  "singular does not handle coefficient maps"
```

2024-04-16 13:33 UTC, simonbrandhorst commented on src/Rings/MPolyMap/AffineAlgebras.jl
> +function preimage(
Did a non-field work before? Such as `ZZ`? Please check / add a test so that we can spot regressions.

2024-04-16 13:33 UTC, simonbrandhorst commented on src/Rings/MPolyMap/AffineAlgebras.jl
> +function preimage(
please add a test for this fix.

2024-04-16 13:33 UTC, simonbrandhorst commented on src/Rings/mpoly-ideals.jl
> +      # In practice this will often lead to significant speedup due to reduction of degrees.
```suggestion
      # In practice this will often lead to significant speedup due to reduction of degrees.
      # TODO:  is the following faster? radical(ab,c) = intersect(radical(a,c),radical(b,c)) 
```

2024-04-16 13:33 UTC, simonbrandhorst commented on src/Rings/mpoly-localizations.jl
>  function simplify!(S::MPolyPowersOfElement)
These changes to `simplify!` should be reverted.

2024-04-16 13:33 UTC, simonbrandhorst commented on src/Rings/mpoly-localizations.jl
> +@attr function dim(I::MPolyLocalizedIdeal{RT}) where {RT<:MPolyLocRing{<:Field, <:FieldElem, <:MPolyRing, <:MPolyRingElem, <:MPolyPowersOfElement}}
```suggestion
@attr function dim(I::MPolyLocalizedIdeal{RT}) where {RT<:MPolyLocRing{<:Ring, <:RingElem, <:MPolyRing, <:MPolyRingElem, <:MPolyPowersOfElement}}
```

2024-04-16 13:33 UTC, simonbrandhorst commented on src/Rings/mpoly-localizations.jl
> +@attr function dim(I::MPolyLocalizedIdeal{RT}) where {RT<:MPolyLocRing{<:Field, <:FieldElem, <:MPolyRing, <:MPolyRingElem, <:MPolyComplementOfPrimeIdeal}}
```suggestion
@attr function dim(I::MPolyLocalizedIdeal{RT}) where {RT<:MPolyLocRing{<:Ring, <:RingElem, <:MPolyRing, <:MPolyRingElem, <:MPolyComplementOfPrimeIdeal}}
```

2024-04-16 13:33 UTC, simonbrandhorst commented on src/Rings/mpolyquo-localizations.jl
> +  if length(terms(lifted_numerator(f))) > 10000
```suggestion
  if length(lifted_numerator(f)) > 10000
```

2024-04-16 13:33 UTC, simonbrandhorst commented on src/Rings/mpolyquo-localizations.jl
> +  if length(terms(lifted_numerator(f))) > 10000
saves us from many allocations

2024-04-16 13:33 UTC, simonbrandhorst commented on src/Rings/mpolyquo-localizations.jl
> +                                     <:MPolyPowersOfElement}})
this needs some benchmarking and/or an algorithm keyword.

2024-04-16 13:33 UTC, simonbrandhorst commented on src/Rings/mpolyquo-localizations.jl
>  @attr MPolyQuoLocalizedIdeal function radical(I::MPolyQuoLocalizedIdeal)
```suggestion
@attr T function radical(I::T) where {T<:MPolyQuoLocalizedIdeal}
```

2024-04-16 13:33 UTC, simonbrandhorst commented on src/Rings/primary_decomposition_helpers.jl
> +#=
check and delete if appropriate

2024-04-16 13:33 UTC, simonbrandhorst commented on src/exports.jl
> -export morphism_of_projective_schemes
remember the deprecation

2024-04-16 13:33 UTC, simonbrandhorst commented on test/AlgebraicGeometry/Schemes/AffineRationalPoint.jl
> +  # @test_throws ErrorException pk == pL # Does not throw anymore. Why?
check if still the case

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/IdealSheaves.jl
> +    dim(I(U)) == dim(I) || continue                  ## components of lesser dimension can be discarded
```suggestion
```
wrong

2024-04-16 13:33 UTC, simonbrandhorst commented on experimental/Schemes/IdealSheaves.jl
> +    @assert all(p->dim(p) == dim(I), components_here) "not all minimal primes have the correct dimension"
```suggestion
```

2024-04-16 13:33 UTC, simonbrandhorst commented on test/AlgebraicGeometry/Schemes/transforms.jl
> +  @test length(L2) == 1
```suggestion
  @test length(L2) == 2
```

2024-04-16 13:33 UTC, simonbrandhorst commented on test/AlgebraicGeometry/Schemes/transforms.jl
> +  @test length(zerosinL2) == 0
```suggestion
  @test length(zerosinL2) == 1
```

2024-04-16 13:33 UTC, simonbrandhorst commented on test/Rings/mpoly-localizations.jl
>    small_gens = small_generating_set(phi2(J))
add the algorithm keyword and test both

2024-04-16 18:56 UTC, HechtiDerLachs commented on experimental/Schemes/IdealSheaves.jl
> +
```suggestion
```

2024-04-17 13:34 UTC, HechtiDerLachs commented
The PR seems to have become a bit bigger, because I moved the type declarations out of `src/Rings/mpoly-localizations.jl`. But that is just code migration and nothing has changed about its internals. 

Other than that, I think I addressed all relevant issues raised by the review.

2024-04-17 14:04 UTC, simonbrandhorst commented on experimental/Schemes/elliptic_surface.jl
> +      continue
do you have proof? ;-)

2024-04-17 14:07 UTC, simonbrandhorst commented
Awsome, thanks a long for this huge piece of work! I wonder if we can soon enable some of the tests that were previously far too slow to ever run.

2024-04-17 14:09 UTC, simonbrandhorst approved these changes

2024-04-17 14:58 UTC, merged