Add proper OSCAR type for tropical polyhedra
oscar-system/Oscar.jl pull request #4001
Opened 2024-08-09 11:54 UTC by ooinaruhugh

Polymake has support for tropical polyhedra, but what is there does not interface so nicely with OSCAR.
This PR serves to add a proper Julia type `TropicalPolyhedron` and provide basic functionality, to fix some design decisions about the data type.

This might also be useful in light of https://github.com/oscar-system/Oscar.jl/pull/3989#pullrequestreview-2217007913.

2024-08-09 11:55 UTC, ooinaruhugh commented
@Sami-Halaseh

2024-08-22 13:10 UTC, ooinaruhugh commented
At the moment, questions that need to be discussed:
- How to handle the bookkeeping accross the strata? (@lkastner Might have an opinion, e.g. the question `Map` vs. indexing strata by bitmasks)
- Regarding the "one polyhedral complex per stratum", vertices need to be renamed. Where to do this, or how to present information on boundary cells?
- More remote question, this is also a welcome addition for polymake. Thus, implement in polymake first and then make accessible from OSCAR, or directly in OSCAR?

2025-05-07 21:14 UTC, fingolfin commented
What the status of this PR?

2025-05-08 22:56 UTC, ooinaruhugh commented
This has been pushed to my backlog over the last few months, but I just finished a great deal of work. So thank you for reminding me of this.

At the moment, I just had some prototype code.

2025-05-09 08:02 UTC, micjoswig commented
Let's first finalize #4061.  Afterwards it will be easier to see how we want to design this.

2025-06-18 00:02 UTC, fingolfin commented
In the meantime #4061 has been merged a few weeks ago. So if @ooinaruhugh is still interested and has some spare time, perhaps this can be brought forward? :-)

2025-06-19 15:57 UTC, micjoswig commented
The overall goal still stands.

To make progress now, we tackle the following slightly simpler problem. first Input: point configuration in tropical projective space; Output: covector decomposition induced on tropical projective torus (which is an ordinary polyhedral complex).  This can be inherited from polymake directly.

2025-06-22 00:50 UTC, ooinaruhugh commented
While testing the `polytope_covector_decomposition`, I noticed inconsistencies regarding what 'pseudovertices' in polymake are. `PSEUDOVERTICES` from polymake gives rays for some reason, and `POLYTOPE_COVECTOR_DECOMPOSITION` does not agree with the visualization of the tropical polytope (from `VISUAL`).
We need to investigate this on the polymake side.

2025-06-23 09:31 UTC, benlorenz commented
> While testing the `polytope_covector_decomposition`, I noticed inconsistencies regarding what 'pseudovertices' in polymake are. `PSEUDOVERTICES` from polymake gives rays for some reason, and `POLYTOPE_COVECTOR_DECOMPOSITION` does not agree with the visualization of the tropical polytope (from `VISUAL`). We need to investigate this on the polymake side.

Can you provide an explicit (polymake) example of this discrepancy?

2025-07-02 21:26 UTC, fingolfin commented
ping @ooinaruhugh

2025-07-02 21:32 UTC, ooinaruhugh commented
The discussed discrepancies meant that we had to fix some parts in `polymake` regarding tropical polytopes. I'll finish the test cases which reflect how the output of the implemented functions should be mathematically speaking. But we have to wait for `v4.14` of `polymake` in the end. Unless I should implement a temporary workaround that's only going to stay for a short time.

2025-07-31 04:21 UTC, ooinaruhugh commented
I've finally implemented testcases for both min- and max-tropical objects. This just needs a couple of eyes to run over and a tag for the release notes, which I can't add.

2025-07-31 07:01 UTC, joschmitt commented
> I've finally implemented testcases for both min- and max-tropical objects. This just needs a couple of eyes to run over and a tag for the release notes, which I can't add.

I added the "use title" label (and changed the title). Feel free to change the title to something that fits better or let me know if you want another label.

2025-07-31 12:39 UTC, lgoettgens reviewed
Two minor things I've seen in a first glance.

One more important point: If I remember correctly, (almost) every field access of a Polymake object should have a type assertion on the julia side to help type inference. Maybe @benlorenz can comment on that

2025-07-31 12:39 UTC, lgoettgens commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +  return length(ind)
You could use `count` instead of taking `length` of `findall`, avoiding the allocation of the findall result

2025-07-31 12:39 UTC, lgoettgens commented on test/TropicalGeometry/tropical_polyhedra.jl
> +  # the following are unbroken with polymake v4.14
Polymake 4.14 has arrived in Oscar in the meantime, so these comments (and maybe also the polymake version checks in this file) are obsolete

2025-07-31 16:48 UTC, ooinaruhugh commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +  return length(ind)
Thanks, I changed the two occurrences of this pattern

2025-08-01 13:42 UTC, micjoswig approved these changes
Looks good to me.

2025-08-01 13:48 UTC, micjoswig commented on test/TropicalGeometry/tropical_polyhedra.jl
> +  # the following are unbroken with polymake v4.14
> Polymake 4.14 has arrived in Oscar in the meantime, so these comments (and maybe also the polymake version checks in this file) are obsolete

Comments removed; version checks (for test cases) left in place for now.

2025-08-01 13:49 UTC, micjoswig approved these changes

2025-08-01 14:39 UTC, lgoettgens commented on src/exports.jl
> +export n_pseudovertices
This is not sorted alphabetically, and it should get an alias to `number_of_pseudovertices` in `src/aliases.jl`

2025-08-01 14:39 UTC, lgoettgens commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +n_vertices(P::TropicalPolyhedron) = size(pm_object(P).VERTICES::AbstractMatrix, 1)
```suggestion
n_vertices(P::TropicalPolyhedron) = nrows(pm_object(P).VERTICES::AbstractMatrix)
```

2025-08-01 14:39 UTC, lgoettgens commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +n_pseudovertices(P::TropicalPointConfiguration) = pm_object(P).PSEUDOVERTICES |> size |> first
```suggestion
n_pseudovertices(P::TropicalPointConfiguration) = pm_object(P).PSEUDOVERTICES |> nrows
```

2025-08-01 14:39 UTC, lgoettgens commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +  return all(!iszero, pm_object(P).VERTICES::AbstractMatrix)
many of these type assertions are not concrete enough to actually help the compiler, thus leading to very poorly inferred code. E.g. look at the following example:
```julia
julia> P = tropical_convex_hull(min, QQ[0 -1 0; 0 -4 -1]);

julia> @inferred is_bounded(P)
ERROR: return type Bool does not match inferred return type Any
```

I don't have experience on how to do this better for polymake matrix types, so it would be best to consult @benlorenz or @lkastner on that

2025-08-01 14:39 UTC, lgoettgens commented on test/TropicalGeometry/tropical_polyhedra.jl
> +@testset "TropicalPolyhedron{$minOrMax}" begin
```suggestion
@testset "TropicalPolyhedron{$minOrMax}" for (minOrMax, __sign, oo) in [(min, 1, inf), (max, -1, -inf)]
```
some suggestion to make this more readable

2025-08-01 14:39 UTC, lgoettgens commented on test/TropicalGeometry/tropical_polyhedra.jl
> +end
```suggestion
```
due to merging of for loop and testset above

2025-08-01 14:39 UTC, lgoettgens commented on test/TropicalGeometry/tropical_polyhedra.jl
> +  @test maximal_covectors(P2) |> first == IncidenceMatrix([[1], [2], [3]]) broken=polymake_version <= v"400.1400.0+0"
reading the `broken` condition again, this states that the test in broken with *the initial yggdrasil build* of polymake 4.14, and all previous versions. The problem with that is that some rebuild of polymake without any update to polymake itself (e.g. due to a new FLINT release), would increase this version number and thus changing the output on the condition.

Is the bug already fixed with polymake 4.14 (and thus polymake_jll 400.1400.0+0), or will the fix only be in the next polymake release after that? Depending on that, I could make a suggetsion on how to change the condition

2025-08-01 14:51 UTC, ooinaruhugh commented on test/TropicalGeometry/tropical_polyhedra.jl
> +  @test maximal_covectors(P2) |> first == IncidenceMatrix([[1], [2], [3]]) broken=polymake_version <= v"400.1400.0+0"
There's a hotfix for the specific thing that breaks the test, so it would still be v4.14.
The last time I spoke with @benlorenz, this was the specific condition I should test for.

2025-08-02 22:08 UTC, benlorenz commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +  return all(!iszero, pm_object(P).VERTICES::AbstractMatrix)
For this example `::Polymake.Matrix{<:Polymake.TropicalNumber}` should work, for rational matrices probably `::Polymake.Matrix{Polymake.Rational}`.

The reason for all this is that there is no type information on these properties and they are unwrapped from generic pointers at runtime.

2025-08-02 22:12 UTC, benlorenz commented on test/TropicalGeometry/tropical_polyhedra.jl
> +  @test maximal_covectors(P2) |> first == IncidenceMatrix([[1], [2], [3]]) broken=polymake_version <= v"400.1400.0+0"
There was some rework for 4.14 which fixed many things but there are some things (that unfortunately lacked proper tests) that are still broken / not yet adapted to the new changes. We wanted to fix this in a patch-release for 4.14, exact versioning of the jll still to be decided upon. We already have a hotfix branch for polymake but the fix seems not yet complete. Kamillo will investigate it next week.

2025-08-03 16:27 UTC, YueRen requested changes
Some quick things I caught, but everything looks really solid over all, good job!

The only major change is to put convention last as input argument, for the sake of consistency with the rest of the tropical package.

2025-08-03 16:27 UTC, YueRen commented on docs/src/TropicalGeometry/tropical_polyhedra.md
> +  - point sets $V$ with infinite coordinates and $\mathrm{tconv}(V)$ inside the tropical projective torus
Quick question regarding these two bullet points.  In case $V$ has "entirely finite coordinates", is $\mathrm{tconv}(V)$ not inside the tropical projective torus? Or why is the "$\mathrm{tconv}(V)$ inside the tropical projective torus" omited in the first bullet point?

In case $\mathrm{tconv}(V)$ is always regarded as a subset of the tropical projective torus, I'd just say that $V$ can be any finite set in $\mathbb{T}^d$ but that $\mathrm{tconv}(V)$ is always regarded as a of $\mathbb{TP}^{d-1}$.

2025-08-03 16:27 UTC, YueRen commented on docs/src/TropicalGeometry/tropical_polyhedra.md
> +- a rational matrix and the tropical addition
```suggestion
- a rational matrix and specifying min- or max-convention
```

2025-08-03 16:27 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +tropical_convex_hull(convention::MinOrMax, V::QQMatrix) = _tropical_convex_hull(TropicalPolyhedron, convention, V)
```suggestion
tropical_convex_hull(V::QQMatrix, convention::MinOrMax=min) = _tropical_convex_hull(TropicalPolyhedron, convention, V)
```

Can you please put `convention` last, make it optional with default min?  

I think there might an unfortunate clash of conventions between the polyhedral part and the tropical part of OSCAR: input which specifies the return type is listed first in the polyhedral part while conventions and tropical semiring maps are listed last in the tropical part (because I'm used to C where optional input has to be last).

2025-08-03 16:27 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +tropical_convex_hull(convention::MinOrMax, V::QQMatrix) = _tropical_convex_hull(TropicalPolyhedron, convention, V)
For the sake of consistency, can you please change all user-facing functions accordingly?  (I'm fine with the non-user facing functions staying the way they are)

2025-08-03 16:27 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +    return Polymake.tropical.polytope_subdivision_as_complex(P.pm_tpolytope, dehomogenize_by-1)::Polymake.BigObject |> polyhedral_complex
```suggestion
    return Polymake.tropical.polytope_subdivision_as_complex(pm_object(P), dehomogenize_by-1)::Polymake.BigObject |> polyhedral_complex
```

2025-08-03 16:27 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +Returns an iterator over the vertices of `P`, that is, a minimal generating set `V`
```suggestion
Return an iterator over the vertices of `P`, that is, a minimal generating set `V`
```

The convention is not to use third person singular (don't ask me why).

2025-08-03 16:27 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +Returns the number of vertices of `P`.
```suggestion
Return the number of vertices of `P`.
```

2025-08-03 16:27 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +Returns an iterator over the pseudovertices of `P` in the tropical projective torus,
```suggestion
Return an iterator over the pseudovertices of `P` in the tropical projective torus, 
```

2025-08-03 16:27 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +Returns an iterator over the maximal covectors with respect to `P`.
```suggestion
Return an iterator over the maximal covectors with respect to `P`.
```

2025-08-03 16:27 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +Returns an iterator over the maximal covectors of `P`.
```suggestion
Return an iterator over the maximal covectors of `P`.
```

2025-09-30 11:02 UTC, ooinaruhugh commented on docs/src/TropicalGeometry/tropical_polyhedra.md
> +  - point sets $V$ with infinite coordinates and $\mathrm{tconv}(V)$ inside the tropical projective torus
The difference is between 'tropical projective torus' and 'tropical projective space'.
If the coordinates are finite, then $\mathrm{tconv}(V)$ is in the t.p. torus, if there are infinite coordinates in $V$,
then $\mathrm{tconv}(V)$ is possibly unbounded. Then, you could possibly look at the points with infinite coordinates, in the t.p. space, but this is not implemented in this PR. 

This text is supposed to mean: "In the inifinite coordinates case, we can do $\mathrm{tconv}(V)\cap\mathbb{R}^d/\mathbb{R}\mathbf{1}$ right now"

2025-10-06 21:52 UTC, fingolfin reviewed
Would be nice to get this merged. There is a bunch of minor code review comments that could be addressed with a few clicks of "apply suggestions". A couple others seem to be resolved and just need to be marked as such.

There is also the issue of the "polymake hotfix", no idea what the status there is?

2025-10-06 21:52 UTC, fingolfin commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +  """
We should not document this constructor (it's internal). Instead there should be a docstring on the `struct` definition itself (so that users can find out what this struct is doing, and ideally also what the proper way for constructing an instance is: e.g. by proving a code example that use suitable functions (`tropical_convex_hull` I am guessing would be one?), or with `@ref`

2025-10-06 21:52 UTC, fingolfin commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +struct TropicalPointConfiguration{M<:MinOrMax} <: PolyhedralObject{QQFieldElem}
```suggestion

struct TropicalPointConfiguration{M<:MinOrMax} <: PolyhedralObject{QQFieldElem}
```

2025-10-06 21:52 UTC, fingolfin commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +  """
same comment as above applies here as well.

2025-10-06 21:52 UTC, fingolfin commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +function tropical_polyhedron(A::QQMatrix, B::QQMatrix, convention::MinOrMax=min)
```suggestion

function tropical_polyhedron(A::QQMatrix, B::QQMatrix, convention::MinOrMax=min)
```

2025-10-06 21:52 UTC, fingolfin commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +n_pseudovertices(P::TropicalPointConfiguration) = pm_object(P).PSEUDOVERTICES |> nrows
This is not meant as a blocker to this PR, it could be removed in a follow-up, but I want to record this point of view here:

I'd greatly prefer if this code did not use the pipeline operator `|>` -- it's just yet another Julia feature that's cool if you know it (I personally like it!), and it's great for the REPL -- but many people writing Julia code will still not be familiar with it, raising the barrier for working on this part of the code.

In fact I just checked, and this operator is used just 4 times in all of Oscar.jl -- twice in `experimental`, and twice in `src`.

2025-10-06 21:52 UTC, fingolfin commented on test/TropicalGeometry/tropical_polyhedra.jl
> +  @test maximal_covectors(P2) |> first == IncidenceMatrix([[1], [2], [3]]) broken=polymake_version <= v"400.1400.0+0"
What's the status of this hotfix?

2025-10-06 21:52 UTC, fingolfin commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +n_points(P::TropicalPointConfiguration) = pm_object(P).POINTS::Polymake.Matrix{<:Polymake.TropicalNumber} |> size |> first
Untested, but, doesn't this also work:
```suggestion
n_points(P::TropicalPointConfiguration) = pm_object(P).POINTS::Polymake.Matrix{<:Polymake.TropicalNumber} |> nrows
```
or even better
```suggestion
n_points(P::TropicalPointConfiguration) = nrows(pm_object(P).POINTS::Polymake.Matrix{<:Polymake.TropicalNumber})
```

2025-10-06 21:52 UTC, fingolfin commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +   ind = findall(1:size(ct, 1)) do i
```suggestion
   ind = findall(1:nrows(ct)) do i
```

2025-10-06 21:52 UTC, fingolfin commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +function Base.show(io::IO, P::TropicalPointConfiguration{M}) where {M<:MinOrMax}
```suggestion

function Base.show(io::IO, P::TropicalPointConfiguration{M}) where {M<:MinOrMax}
```

2025-10-06 22:18 UTC, benlorenz commented
> There is also the issue of the "polymake hotfix", no idea what the status there is?

It was released as part of polymake 4.15 and is available as polymake_jll-400.1500.000. This version is already in use by Oscar.
Strictly speaking we could either add a compat entry for `polymake_jll` to enforce this, or set `broken= pmversion < v"400.1500.0"` but I don't think this is necessary since there is nothing else that could block this update.

2025-10-07 07:01 UTC, YueRen requested changes
Looks great, here just some minor nitpicks.

2025-10-07 07:01 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +  Constructs a `TropicalPolyhedron` corresponding to a `Polymake.BigObject` with tropical addition `M`.
```suggestion
  Construct a `TropicalPolyhedron` corresponding to a `Polymake.BigObject` with tropical addition `M`.
```

Consistency with other parts of OSCAR code.

2025-10-07 07:01 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +  Constructs a `TropicalPointConfiguration` corresponding to a `Polymake.BigObject` with tropical addition `M`.
```suggestion
  Construct a `TropicalPointConfiguration` corresponding to a `Polymake.BigObject` with tropical addition `M`.
```

Consistency with other parts of OSCAR code.

2025-10-07 07:01 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +julia> A = TT.(identity_matrix(QQ, 3));
```suggestion
julia> T = tropical_semiring(max);

julia> A = T.(identity_matrix(QQ, 3));
```

Consistency with other tropical docu.

2025-10-07 07:01 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +julia> A = TT[0 -4 -1; 0 -1 0];
```suggestion
julia> A = T[0 -4 -1; 0 -1 0];
```

Consistency with other tropical docu.

2025-10-07 07:01 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +julia> A = TT.(identity_matrix(QQ, 3));
```suggestion
julia> T = tropical_semiring(max);

julia> A = T.(identity_matrix(QQ, 3));
```

Consistency with other tropical docu.

2025-10-07 07:01 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +julia> A = TT[0 -4 -1; 0 -1 0];
```suggestion
julia> A = T[0 -4 -1; 0 -1 0];
```

Consistency with other tropical docu.

2025-10-07 07:01 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +Constructs the tropical point configuration of the vertices `V` in the tropical projective torus
```suggestion
Construct the tropical point configuration of the vertices `V` in the tropical projective torus
```

2025-10-07 07:01 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +Constructs the tropical convex hull of the vertices `V` in the tropical projective torus
```suggestion
Construct the tropical convex hull of the vertices `V` in the tropical projective torus
```

2025-10-07 07:01 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +Constructs the tropical point configuration of the vertices `V` in the tropical projective torus
```suggestion
Construct the tropical point configuration of the vertices `V` in the tropical projective torus
```

2025-10-07 07:01 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +Constructs the tropical convex hull of the vertices `V` in the tropical projective torus
```suggestion
Construct the tropical convex hull of the vertices `V` in the tropical projective torus
```

2025-10-07 07:01 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +Constructs a `TropicalPolyhedron` as the set of points in the tropical projective torus satisfying the inequalities $A\odot x\leq B\odot x$
```suggestion
Construct a `TropicalPolyhedron` as the set of points in the tropical projective torus satisfying the inequalities $A\odot x\leq B\odot x$
```

2025-10-07 07:01 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +Defines a point configuration containing a tropical unit ball in the 2-dimensional tropical projective torus with `max` as addition:
```suggestion
Define a point configuration containing a tropical unit ball in the 2-dimensional tropical projective torus with `max` as addition:
```

2025-10-07 07:01 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/constructors.jl
> +Defines a point configuration containing a tropical unit ball in the 2-dimensional tropical projective torus with `max` as addition:
```suggestion
Define a point configuration containing a tropical unit ball in the 2-dimensional tropical projective torus with `max` as addition:
```

2025-10-07 07:01 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +julia> Q = tropical_convex_hull(TT[0 1 2; inf 0 3; inf inf 0; 0 1 0]);
```suggestion
julia> T = tropical_semiring();

julia> Q = tropical_convex_hull(T[0 1 2; inf 0 3; inf inf 0; 0 1 0]);
```

2025-10-07 07:01 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +  )
```suggestion
  return SubObjectIterator{as}(P, _pseudovertices, n)
```

To be consistent with code below.

2025-10-07 07:01 UTC, YueRen commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +  TT = tropical_semiring(convention(P))
```suggestion
```

This line appears to be unnecessary.

2025-10-08 21:33 UTC, fingolfin approved these changes
Looks good to me, thank you very much!

2025-10-09 08:57 UTC, benlorenz commented on src/TropicalGeometry/TropicalPolyhedron/properties.jl
> +    n_vertices(P::TropicalPointConfiguration)
```suggestion
    n_points(P::TropicalPointConfiguration)
```
(according to the doctest and code below)

2025-10-10 06:41 UTC, YueRen approved these changes
Strong approve.

2025-10-10 09:20 UTC, merged